id: P006688
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14722
  title: 琉璃明镜
  author: ''
  volumes:
    0006b16a2f794a209c3ffae1961cc978:
      image_group_id: I4PD4490
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
